@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.dpeter99.arcanerituals.crafting.altarcrafting;


import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;