@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.dpeter99.arcanerituals.items;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;