@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.dpeter99.arcanerituals.screens.graphicalelements;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;