@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.dpeter99.arcanerituals.screens.graphicalelements;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;